Xs_test = ['topic', 'TextCluster', 'DistanceTo1thCluster', 'DistanceTo2thCluster',
       'DistanceTo3thCluster', 'DistanceTo4thCluster', 'DistanceTo5thCluster',
       'DistanceTo6thCluster', 'DistanceTo7thCluster', 'DistanceTo8thCluster',
       'DistanceTo9thCluster', 'DistanceTo10thCluster',
       'DistanceTo11thCluster', 'DistanceTo12thCluster',
       'DistanceTo13thCluster', 'DistanceTo14thCluster',
       'DistanceTo15thCluster', 'gender', 'age', 'country_tier_1',
       'country_tier_2', 'country_tier_3', 'city_Saint Petersburg',
       'city_tier_1', 'city_tier_2', 'city_tier_3', 'city_tier_4',
       'city_tier_5', 'os_iOS', 'source_organic', 'exp_group_1', 'exp_group_2',
       'exp_group_3', 'exp_group_4', 'hour', 'month', 'weekday']

Xs_control = ['gender', 'age',
       'country_tier_1', 'country_tier_2', 'country_tier_3',
       'city_Saint Petersburg', 'city_tier_1', 'city_tier_2', 'city_tier_3',
       'city_tier_4', 'city_tier_5', 'os_iOS', 'source_organic',
       'exp_group_1', 'exp_group_2',
       'exp_group_3', 'exp_group_4',
       'topic_covid', 'topic_entertainment', 'topic_movie', 'topic_politics',
       'topic_sport', 'topic_tech']